### ISSUE TITLE
Adding flexible content

### ISSUE THREAD

**Issue by pixo-landi** [nlemoine/wp-cli-fixtures#10]
Hi, 

I have an ACF flexible content field to add "components", groups of acf fields, to a custom post type. All the fixtures I have made so far are working well. How would I add a flexible content field?

This is what I am trying so far:
```
Hellonico\Fixtures\Entity\Post:
    post{1..2}:
        post_type: 'blog'
        post_title (unique): '<words(4, true)>'
        post_date: '<dateTimeThisDecade()>'
        acf:
            byline: '<firstName()> <lastName()>'
            intro: '<words(20, true)>'
            add_image: 'true'
            featured_image:  '@featured_images*->ID'
            featured_image_alt_text: '<words(4, true)>'
            components:
                - 'text'
                - 'image'
            components_0_header: '<words(4, true)>'
            components_0_rich_text: <paragraphs(2, true)>
            components_0_add_image: 'true'
            components_0_image: '@pics*->ID'
            components_0_image_alt_text: '<words(4, true)>'
            components_0_placement: 'right'
            components_0_size: 'half'
            components_1_image: '@pics*->ID'
            components_1_image_alt_text: '<words(4, true)>'
```

and this is what a dump of the $post looks like:
``` Rareloop\Lumberjack\Post {#1375 ▼
  +ImageClass: "Timber\Image"
  +PostClass: "Timber\Post"
  +TermClass: "Timber\Term"
  +object_type: "post"
  +custom: array:32 [▼
    "_fake" => "1"
    "_wp_old_date" => "2021-10-28"
    "byline" => "Allison Runolfsson"
    "_byline" => "field_blog_byline"
    "intro" => "sed a nam et sint autem inventore aut officia aut aut blanditiis et ducimus eos odit amet et est ut"
    "_intro" => "field_blog_intro"
    "add_image" => "1"
    "_add_image" => "field_blog_add_image"
    "featured_image" => "76"
    "_featured_image" => "field_blog_featured_image"
    "featured_image_alt_text" => "nisi molestiae quidem ut"
    "_featured_image_alt_text" => "field_blog_featured_image_alt_text"
    "components" => array:2 [▼
      0 => "text"
      1 => "image"
    ]
    "_components" => "field_blog_components"
    "_edit_lock" => "1635428232:1"
    "_edit_last" => "1"
    "featured_image_caption" => ""
    "_featured_image_caption" => "field_blog_featured_image_caption"
    "components_0_header" => "header"
    "_components_0_header" => "field_blog_components_text_header"
    "components_0_hide_header" => "0"
    "_components_0_hide_header" => "field_blog_components_text_hide_header"
    "components_0_rich_text" => "rich text"
    "_components_0_rich_text" => "field_blog_components_text_rich_text"
    "components_0_add_image" => "0"
    "_components_0_add_image" => "field_blog_components_text_add_image"
    "components_1_image" => "76"
    "_components_1_image" => "field_blog_components_image_image"
    "components_1_image_alt_text" => "field"
    "_components_1_image_alt_text" => "field_blog_components_image_image_alt_text"
    "components_1_image_caption" => ""
    "_components_1_image_caption" => "field_blog_components_image_image_caption"
  ]```

Any guidance would be appreciated.
