### ISSUE TITLE
Translatable content and fixtures

### ISSUE THREAD

**Issue by HansCz** [nlemoine/wp-cli-fixtures#5]
Have you given any thought to how you might handle translations of fixtures?
For example how to handle fixtures on sites using WPML?

Given the following:

````
#
# TERMS
#
Hellonico\Fixtures\Entity\Term:
  focus_areas{1..4}: # custom taxonomy
    name (unique): <words(3, true)> # '(unique)' is required
    description: <sentences(1, true)>
    taxonomy: focus_area

#
# POSTS
#
Hellonico\Fixtures\Entity\Post:
  default (template):
    post_title: <words(2, true)>
    post_date: <dateTimeThisDecade()>
    post_content: <paragraphs(5, true)>
    post_excerpt: <paragraphs(1, true)>

  projects_with_focus_area_1_{1..5}:
      __construct: [<postId(post_type=projects&post_status=publish)>]
      tax_input:
        focus_area: '@focus_areas1->term_id'
````
I can relate the generated terms just fine to the existing posts, but the `<postID()>` function does not stick to fetching posts in the default language. It randomly fetches posts regardless of their language. Would you be interested in a fix for this?

I imagine checking if WPML is running, and if so, limit the post query to only fetch posts in the default language.
