### ISSUE TITLE
How to use before value in Yaml file

### ISSUE THREAD

**Issue by mehrshaddarzi** [nlemoine/wp-cli-fixtures#9]
Please See this yml File:

```
Hellonico\Fixtures\Entity\User:
  user{1..10}:
    user_login (unique): <username()> # '(unique)' is required
    user_pass: 123
    user_email: <freeEmail()>
    user_url: <url()>
    user_registered: <dateTimeThisDecade()>
    first_name: <firstName()>
    last_name: <lastName()>
    description: <sentence()>
    role: <randomElement(['subscriber', 'editor'])>
    meta:
      show_admin_bar_front: 'false'
      billing_phone: <phoneNumber()>
      billing_country: 'IR'
      billing_state: <randomElement(['ABZ','ADL','EAZ','WAZ','BHR','CHB','FRS','GIL','GLS','HDN','HRZ','ILM','ESF','KRN','KRH','NKH','RKH','SKH','KHZ','KBD','KRD','LRS','MKZ','MZN','GZN','QHM','SMN','SBN','THR','YZD','ZJN'])>
      billing_city: <city()>
      billing_address_1: <streetAddress()>
      billing_postcode: <postcode()>
      billing_email: <freeEmail()>
      billing_first_name: <firstName()>
      billing_last_name: <lastName()>
```

I want to `billing_first_name` =` first_name` when creating this user in any loop?

### Problem 2

```
#
# POSTS
#
Hellonico\Fixtures\Entity\Post:

  # TEMPLATE
  defaultpost (template):
    post_title: <words(5, true)>
    post_date: <dateTimeThisDecade()>
    post_content: <paragraphs(5, true)>
    post_excerpt: <paragraphs(1, true)>

  # CUSTOM POST TYPE
  product{1..15} (extends defaultpost):
    post_type: product
    meta:
      _thumbnail_id: '@custom_images*->ID'
    meta_input:
      _sku: <numberBetween(1000, 2000)>
      _regular_price: <numberBetween(10000, 20000)>
      _price: <numberBetween(10000, 20000)>
      _sale_price: <numberBetween(10000, 20000)>
      _stock_status: 'instock'
      _manage_stock: 'yes'
      _stock: <numberBetween(1, 10)>
```

I Want to `_sale_price` = `_price`. how to use before value in YAML?

thanks

**Comment by jenkoian** [comment]
Not tested this at all, but could you use [@self](https://github.com/nelmio/alice/blob/master/doc/relations-handling.md#self-reference) ?

e.g. 
```yaml
billing_first_name: '@self->first_name'
...
_sale_price: '@self->_price'
```
